### ISSUE TITLE
readme-stat does not work well

### ISSUE THREAD

**Issue by NeumoNeumo** [GuTaoZi/GuTaoZi#1]
As shown in this picture, the readme-stat encounters an error.
![image](https://user-images.githubusercontent.com/107997665/220654899-44ab6035-ccf2-4e95-9a2f-f87898945052.png)

Possible solutions could be found in Issues like [1](https://github.com/anuraghazra/github-readme-stats/issues/2149), [2](https://github.com/anuraghazra/github-readme-stats/issues/2404) and [3](https://github.com/anuraghazra/github-readme-stats/issues/2402) :smiley:

**Comment by GuTaoZi** [comment]
Gotcha. Great thanks for informing me of this exception, it's now fixed with the step-by-step solution [here](https://github.com/anuraghazra/github-readme-stats#deploy-on-your-own-vercel-instance).
Btw it's now counting operations on my private repos as well, though I don't really have any ; )
